services:
  kitchen-server:
    build:
      context: .
      dockerfile: kitchen_server/Dockerfile
      target: development
    volumes:
      - ./kitchen_server/src:/app/kitchen_server/src:ro
      - ./kitchen_server/tsconfig.json:/app/kitchen_server/tsconfig.json:ro
      - ./kitchen_database/dist:/app/kitchen_database/dist:ro
      - ./kitchen_station/dist:/app/kitchen_station/dist:ro
    environment:
      - NODE_ENV=development

  kitchen-dashboard:
    build:
      context: ./kitchen_dashboard
      target: development
    volumes:
      - ./kitchen_dashboard/src:/dashboard/src:ro
      - ./kitchen_dashboard/tsconfig.json:/dashboard/tsconfig.json:ro
    environment:
      - NODE_ENV=development
